### ISSUE TITLE
deprecated kubelet flags

### ISSUE THREAD

**Issue by pblaas** [pblaas/nagoya#4]
Some kubelet flags currently used are deprecated and need to be removed.
Some flags need to be moved to the kubelet config file instead of invoking the flag directory on the kubelet.

Need to be removed:
--register-schedulable has been deprecated, will be removed in a future version
--allow-privileged has been deprecated, will be removed in a future version

Need to be moved to a new config file:
--pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag.
--cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. 
--cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. 
--client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. 
--anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. 
--http-check-frequency has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. 
--node-status-update-frequency has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. 
--volume-stats-agg-period has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag.

**Comment by pblaas** [comment]
Proposed new config file could look like this:

```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: false
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.pem
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
cgroupsPerQOS: true
clusterDNS:
- 10.3.0.10
clusterDomain: cluster.local
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuManagerPolicy: none
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enforceNodeAllocatable:
- pods
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
fileCheckFrequency: 20s
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kubeAPIBurst: 10
kubeAPIQPS: 5
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 110
nodeStatusUpdateFrequency: 30s
oomScoreAdj: -999
podPidsLimit: -1
port: 10250
ReadOnlyPort: 10255
registryBurst: 10
registryPullQPS: 5
resolvConf: /etc/resolv.conf
rotateCertificates: false
runtimeRequestTimeout: 2m0s
serializeImagePulls: true
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
volumeStatsAggPeriod: 2m0s
```
ref links:
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#create-the-config-file
https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/kubelet/apis/kubeletconfig/v1beta1/types.go
